### ISSUE TITLE
ProjectDir sometimes ends with '\' 

### ISSUE THREAD

**Issue by teytelbaum** [footcha/MSBuildExtensions#1]
Need to remove '\' when using $(ProjectDir) variable

Change line 
`<AssemblyInfoFilePath Condition=" '$(AssemblyInfoFilePath)' == '' ">$(ProjectDir)\Properties\AssemblyInfo.cs</AssemblyInfoFilePath>`
to 
`<AssemblyInfoFilePath Condition=" '$(AssemblyInfoFilePath)' == '' ">$(ProjectDir.TrimEnd('\'))\Properties\AssemblyInfo.cs</AssemblyInfoFilePath>`

**Comment by footcha** [comment]
Hello @teytelbaum,
thank you for reporting this issue. I will fix it during weekend.
Kind regards,
Petr

**Comment by footcha** [comment]
I do apologise for long delay with solving this issue. Now an issue is fixed. Please check new Nuget package.

**Comment by footcha** [comment]
Hello @teytelbaum,
can I close this issue, please?
