### ISSUE TITLE
developmentDependency="true"

### ISSUE THREAD

**Issue by teytelbaum** [footcha/MSBuildExtensions#2]
> from MSDN
> developmentDependency | (2.8+) A Boolean value specifying whether the package is be marked as a development-only-dependency, which prevents the package from being included as a dependency in other packages.
> 

Want to have your package as developmentDependency for not adding it as nuget dependency.
So, in a package config file MSBuild.AssemblyVersion should look like this:
`<package id="MSBuild.AssemblyVersion" version="1.1.0.0" targetFramework="net461" developmentDependency="true" />
`  
As I understand in your nuspec file add 
<developmentDependency>true</developmentDependency>

**Comment by footcha** [comment]
Hello @teytelbaum,
Thank you for reporting this issue.
I will fix this during a weekend.
Kind regards,
Petr

**Comment by footcha** [comment]
I do apologise for long delay with solving this issue. Now an issue is fixed. Please check new Nuget package.

**Comment by footcha** [comment]
Hello @teytelbaum,
can I close this issue, please?
