### ISSUE TITLE
Great job man, it solved my assembly version not matching published version

### ISSUE THREAD

**Issue by martienpoels-bank2loyalty** [footcha/MSBuildExtensions#6]
Just wanted to leave a note how happy I'm with this solution. Now I could set the assembly version right from devops buildscript. Realy a method I was looking for. Thanks a lot!

**Comment by martienpoels-bank2loyalty** [comment]
(Not to have you worry it is an issue)

**Comment by footcha** [comment]
Perfect. Thank you. I am happy that a rather old piece of code helped you.
